import React, { createContext, useContext, useState, useCallback } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Navigation
  'nav.dashboard': { pt: 'Painel', en: 'Dashboard' },
  'nav.shipments': { pt: 'Embarques', en: 'Shipments' },
  'nav.quotes': { pt: 'Cotações', en: 'Quotes' },
  'nav.registrations': { pt: 'Cadastros', en: 'Registrations' },
  'nav.financial': { pt: 'Financeiro', en: 'Financial' },
  'nav.overhead': { pt: 'Contas Fixas', en: 'Fixed Expenses' },
  'nav.settings': { pt: 'Configurações', en: 'Settings' },
  'nav.billing': { pt: 'Assinatura', en: 'Billing' },
  'nav.logout': { pt: 'Sair', en: 'Logout' },
  'nav.support': { pt: 'Suporte', en: 'Support' },

  // Dashboard
  'dashboard.title': { pt: 'Painel de Controle', en: 'Dashboard' },
  'dashboard.welcome': { pt: 'Bem-vindo de volta', en: 'Welcome back' },
  'dashboard.priority_tasks': { pt: 'Tarefas Prioritárias', en: 'Priority Tasks' },
  'dashboard.active_shipments': { pt: 'Embarques Ativos', en: 'Active Shipments' },
  'dashboard.revenue_mtd': { pt: 'Receita do Mês', en: 'Revenue MTD' },
  'dashboard.pending_approvals': { pt: 'Aprovações Pendentes', en: 'Pending Approvals' },
  'dashboard.overdue_tasks': { pt: 'Tarefas Atrasadas', en: 'Overdue Tasks' },
  'dashboard.recent_activity': { pt: 'Atividade Recente', en: 'Recent Activity' },
  'dashboard.quick_actions': { pt: 'Ações Rápidas', en: 'Quick Actions' },
  'dashboard.new_shipment': { pt: 'Novo Embarque', en: 'New Shipment' },
  'dashboard.new_quote': { pt: 'Nova Cotação', en: 'New Quote' },
  'dashboard.send_followup': { pt: 'Enviar Follow-up', en: 'Send Follow-up' },
  'dashboard.view_all': { pt: 'Ver Todos', en: 'View All' },
  'dashboard.drafts_expiring': { pt: 'Drafts vencendo hoje', en: 'Drafts expiring today' },
  'dashboard.quotes_pending': { pt: 'Cotações aguardando aprovação', en: 'Quotes awaiting approval' },
  'dashboard.docs_missing': { pt: 'Documentos faltando', en: 'Documents missing' },

  // Shipments
  'shipments.title': { pt: 'Embarques', en: 'Shipments' },
  'shipments.new': { pt: 'Novo Embarque', en: 'New Shipment' },
  'shipments.search': { pt: 'Buscar embarques...', en: 'Search shipments...' },
  'shipments.reference': { pt: 'Referência', en: 'Reference' },
  'shipments.client': { pt: 'Cliente', en: 'Client' },
  'shipments.origin': { pt: 'Origem', en: 'Origin' },
  'shipments.destination': { pt: 'Destino', en: 'Destination' },
  'shipments.pickup': { pt: 'Coleta', en: 'Pickup' },
  'shipments.delivery': { pt: 'Entrega', en: 'Delivery' },
  'shipments.mode': { pt: 'Modo', en: 'Mode' },
  'shipments.status': { pt: 'Status', en: 'Status' },
  'shipments.etd': { pt: 'ETD', en: 'ETD' },
  'shipments.eta': { pt: 'ETA', en: 'ETA' },
  'shipments.overview': { pt: 'Visão Geral', en: 'Overview' },
  'shipments.logistics': { pt: 'Logística', en: 'Logistics' },
  'shipments.revert_to_quote': { pt: 'Reverter para Cotação', en: 'Revert to Quote' },
  'shipments.revert_confirm_title': { pt: 'Reverter Embarque para Cotação?', en: 'Revert Shipment to Quote?' },
  'shipments.revert_confirm_desc': { pt: 'O embarque será excluído e a cotação voltará ao status de rascunho. Todas as cobranças, documentos e registros de atividade do embarque serão removidos. Esta ação não pode ser desfeita.', en: 'The shipment will be deleted and the quote will return to draft status. All charges, documents and activity logs from the shipment will be removed. This action cannot be undone.' },
  'shipments.reverted_to_quote': { pt: 'Embarque revertido para cotação com sucesso!', en: 'Shipment successfully reverted to quote!' },
  'shipments.financial': { pt: 'Financeiro', en: 'Financial' },
  'shipments.documents': { pt: 'Documentos', en: 'Documents' },
  'shipments.activity': { pt: 'Atividade', en: 'Activity' },
  'shipments.quick_create': { pt: 'Criação Rápida', en: 'Quick Create' },
  'shipments.carrier': { pt: 'Transportadora', en: 'Carrier' },
  'shipments.incoterm': { pt: 'Incoterm', en: 'Incoterm' },
  'shipments.cargo_desc': { pt: 'Descrição da Carga', en: 'Cargo Description' },

  // Statuses
  'status.draft': { pt: 'Rascunho', en: 'Draft' },
  'status.quoted': { pt: 'Cotado', en: 'Quoted' },
  'status.booked': { pt: 'Reservado', en: 'Booked' },
  'status.collected_at_origin': { pt: 'Coletado', en: 'Collected' },
  'status.docs_at_origin': { pt: 'Docs', en: 'Docs' },
  'status.in_transit': { pt: 'Trânsito', en: 'Transit' },
  'status.arrived': { pt: 'Chegou', en: 'Arrived' },
  'status.delivered': { pt: 'Entregue', en: 'Delivered' },
  'status.cancelled': { pt: 'Cancelado', en: 'Cancelled' },

  // Transport modes
  'mode.ocean_fcl': { pt: 'Marítimo FCL', en: 'Ocean FCL' },
  'mode.ocean_lcl': { pt: 'Marítimo LCL', en: 'Ocean LCL' },
  'mode.air': { pt: 'Aéreo', en: 'Air' },
  'mode.road': { pt: 'Rodoviário', en: 'Road' },
  'mode.multimodal': { pt: 'Multimodal', en: 'Multimodal' },

  // Quotes
  'quotes.title': { pt: 'Cotações', en: 'Quotes' },
  'quotes.new': { pt: 'Nova Cotação', en: 'New Quote' },
  'quotes.number': { pt: 'Número', en: 'Number' },
  'quotes.valid_until': { pt: 'Válida até', en: 'Valid Until' },
  'quotes.total': { pt: 'Total', en: 'Total' },
  'quotes.profit': { pt: 'Lucro', en: 'Profit' },
  'quotes.select_mode': { pt: 'Selecione o Modal', en: 'Select Transport Mode' },
  'quotes.select_mode_desc': { pt: 'Escolha o modal de transporte para esta cotação. Os campos serão adaptados automaticamente.', en: 'Choose the transport mode for this quote. Fields will adapt automatically.' },
  'quotes.step_details': { pt: 'Detalhes da Cotação', en: 'Quote Details' },
  'quotes.continue': { pt: 'Continuar', en: 'Continue' },
  'quotes.back': { pt: 'Voltar', en: 'Back' },
  'quotes.save_draft': { pt: 'Salvar Rascunho', en: 'Save Draft' },
  'quotes.select_client': { pt: 'Selecionar cliente...', en: 'Select client...' },
  'quotes.search_port': { pt: 'Buscar porto/aeroporto...', en: 'Search port/airport...' },
  'quotes.cargo_details': { pt: 'Detalhes da Carga', en: 'Cargo Details' },
  'quotes.container_type': { pt: 'Tipo Container', en: 'Container Type' },
  'quotes.container_qty': { pt: 'Qtd Containers', en: 'Container Qty' },
  'quotes.weight_kg': { pt: 'Peso (kg)', en: 'Weight (kg)' },
  'quotes.volume_cbm': { pt: 'Volume (m³)', en: 'Volume (cbm)' },
  'quotes.chargeable_weight': { pt: 'Peso Taxável (kg)', en: 'Chargeable Weight (kg)' },
  'quotes.length_cm': { pt: 'Comp. (cm)', en: 'Length (cm)' },
  'quotes.width_cm': { pt: 'Larg. (cm)', en: 'Width (cm)' },
  'quotes.height_cm': { pt: 'Alt. (cm)', en: 'Height (cm)' },
  'quotes.packages': { pt: 'Volumes', en: 'Packages' },
  'quotes.commodity': { pt: 'Mercadoria', en: 'Commodity' },
  'quotes.dangerous_goods': { pt: 'Carga Perigosa (IMO/DGR)', en: 'Dangerous Goods (IMO/DGR)' },
  'quotes.vehicle_type': { pt: 'Tipo de Veículo', en: 'Vehicle Type' },
  'quotes.notes': { pt: 'Observações', en: 'Notes' },
  'quotes.notes_placeholder': { pt: 'Observações adicionais...', en: 'Additional notes...' },
  'quotes.ncm_code': { pt: 'NCM', en: 'NCM Code' },
  'quotes.add_item': { pt: 'Adicionar Item', en: 'Add Item' },
  'quotes.item': { pt: 'Item', en: 'Item' },
  'quotes.totals': { pt: 'Totais Calculados', en: 'Calculated Totals' },
  'quotes.total_cbm': { pt: 'Cubagem Total', en: 'Total CBM' },
  'quotes.total_chargeable': { pt: 'Peso Taxado', en: 'Chargeable Weight' },
  'quotes.sell': { pt: 'Venda', en: 'Sell' },
  'quotes.buy': { pt: 'Compra', en: 'Buy' },
  'quotes.general': { pt: 'Geral', en: 'General' },
  'quotes.cargo': { pt: 'Resumo da Carga', en: 'Cargo Summary' },
  'quotes.charges': { pt: 'Compra/Venda', en: 'Buy/Sell' },
  'quotes.add_charge': { pt: 'Adicionar', en: 'Add' },
  'quotes.comments': { pt: 'Comentários', en: 'Comments' },
  'quotes.add_comment': { pt: 'Adicionar comentário...', en: 'Add comment...' },
  'quotes.comment_added': { pt: 'Comentário adicionado', en: 'Comment added' },
  'quotes.billing_unit': { pt: 'Base', en: 'Unit' },
  'quotes.billing_fixed': { pt: 'Fixo', en: 'Fixed' },
  'quotes.billing_per_ton': { pt: 'Por Ton', en: 'Per Ton' },
  'quotes.billing_per_cbm': { pt: 'Por M³', en: 'Per M³' },
  'quotes.billing_per_wm': { pt: 'Ton/M³ (W/M)', en: 'Ton/M³ (W/M)' },
  'quotes.billing_per_cw': { pt: 'Peso Taxado', en: 'Chg. Weight' },
  'quotes.billing_per_container': { pt: 'Por Container', en: 'Per Container' },
  'quotes.billing_per_container_20': { pt: "Por Container 20'", en: "Per Container 20'" },
  'quotes.billing_per_container_40': { pt: "Por Container 40'", en: "Per Container 40'" },
  'quotes.billing_per_bl': { pt: 'Por BL', en: 'Per BL' },
  'quotes.billing_percent': { pt: 'Percentual', en: 'Percent' },
  'quotes.total_buy': { pt: 'Total Compra', en: 'Total Buy' },
  'quotes.total_sell': { pt: 'Total Venda', en: 'Total Sell' },
  'quotes.details': { pt: 'Detalhes da Cotação', en: 'Quote Details' },
  'quotes.leg': { pt: 'Trecho', en: 'Leg' },
  'quotes.leg_origin': { pt: 'Origem', en: 'Origin' },
  'quotes.leg_freight': { pt: 'Frete', en: 'Freight' },
  'quotes.leg_destination': { pt: 'Destino', en: 'Destination' },
  'quotes.select_charge': { pt: 'Selecionar charge...', en: 'Select charge...' },
  'quotes.add_buy': { pt: 'Compra', en: 'Buy' },
  'quotes.add_sell': { pt: 'Venda', en: 'Sell' },
  'quotes.partners_tab': { pt: 'Empresas', en: 'Companies' },
  'quotes.add_partner': { pt: 'Buscar empresa...', en: 'Search company...' },
  'quotes.partner_added': { pt: 'Empresa adicionada', en: 'Company added' },
  'quotes.partner_removed': { pt: 'Empresa removida', en: 'Company removed' },
  'quotes.no_partners': { pt: 'Nenhuma empresa adicionada. Adicione empresas para poder selecioná-las nas taxas.', en: 'No companies added. Add companies to select them in charges.' },
  'common.add': { pt: 'Adicionar', en: 'Add' },
  'common.select': { pt: 'Selecionar...', en: 'Select...' },
  'quotes.save_changes': { pt: 'Salvar Alterações', en: 'Save Changes' },
  'quotes.changes_saved': { pt: 'Alterações salvas com sucesso', en: 'Changes saved successfully' },
  'quotes.clone_to_sell': { pt: 'Clonar para Venda', en: 'Clone to Sell' },
  'quotes.clone_to_buy': { pt: 'Clonar para Compra', en: 'Clone to Buy' },
  'quotes.generate_pdf': { pt: 'Gerar PDF', en: 'Generate PDF' },
  'quotes.pdf_preview': { pt: 'Pré-visualização da Proposta', en: 'Quote Preview' },
  'quotes.download_pdf': { pt: 'Baixar PDF', en: 'Download PDF' },
  'quotes.pdf_downloaded': { pt: 'PDF baixado com sucesso', en: 'PDF downloaded successfully' },
  'quotes.mark_approved': { pt: 'Aprovado', en: 'Approved' },
  'quotes.approved_success': { pt: '🎉 Cotação aprovada com sucesso!', en: '🎉 Quote approved successfully!' },
  'quotes.converted_to_shipment': { pt: '🎉 Cotação aprovada e embarque criado!', en: '🎉 Quote approved and shipment created!' },
  'quotes.duplicate': { pt: 'Duplicar Cotação', en: 'Duplicate Quote' },
  'quotes.duplicate_desc': { pt: 'Duplique esta cotação para outro modal, ajustando origem, destino e incoterm. A carga será copiada.', en: 'Duplicate this quote for another mode, adjusting origin, destination and incoterm. Cargo will be copied.' },
  'quotes.duplicated_success': { pt: 'Cotação duplicada com sucesso', en: 'Quote duplicated successfully' },
  'shipments.duplicate': { pt: 'Duplicar Embarque', en: 'Duplicate Shipment' },
  'shipments.duplicate_desc': { pt: 'Cria uma nova cotação a partir deste embarque, copiando origem, destino, modal e carga. Ajuste antes de confirmar.', en: 'Create a new quote from this shipment, copying origin, destination, mode and cargo. Adjust before confirming.' },
  'shipments.duplicated_success': { pt: 'Embarque duplicado como nova cotação', en: 'Shipment duplicated as new quote' },
  'quotes.mark_sent': { pt: 'Marcar como enviada', en: 'Mark as sent' },
  'quotes.sent_at': { pt: 'Enviada em', en: 'Sent at' },
  'quotes.not_sent_warning': { pt: '⚠️ Cotação não enviada há mais de 24h', en: '⚠️ Quote not sent for over 24h' },
  'quotes.marked_sent_success': { pt: 'Cotação marcada como enviada', en: 'Quote marked as sent' },
  'quotes.reject': { pt: 'Recusar Cotação', en: 'Reject Quote' },
  'quotes.reject_desc': { pt: 'Informe o motivo da recusa desta cotação.', en: 'Enter the reason for rejecting this quote.' },
  'quotes.reject_reason': { pt: 'Justificativa', en: 'Reason' },
  'quotes.reject_reason_placeholder': { pt: 'Motivo da recusa...', en: 'Rejection reason...' },
  'quotes.reject_confirm': { pt: 'Confirmar Recusa', en: 'Confirm Rejection' },
  'quotes.rejected_success': { pt: 'Cotação recusada', en: 'Quote rejected' },
  'quotes.month_total': { pt: 'Cotações no Mês', en: 'Quotes This Month' },
  'quotes.pending_response': { pt: 'Aguardando Resposta', en: 'Pending Response' },
  'quotes.converted_count': { pt: 'Convertidas em Embarque', en: 'Converted to Shipment' },


  'charges.catalog': { pt: 'Catálogo de Taxas', en: 'Tax Catalog' },
  'charges.new': { pt: 'Nova Taxa', en: 'New Tax' },
  'charges.name': { pt: 'Nome', en: 'Name' },
  'charges.type': { pt: 'Trecho', en: 'Leg' },
  'charges.tab': { pt: 'Taxas', en: 'Taxes' },

  'quotes.incoterm': { pt: 'Incoterm', en: 'Incoterm' },
  'quotes.transit_time': { pt: 'Transit Time (dias)', en: 'Transit Time (days)' },
  'quotes.free_time': { pt: 'Free Time (dias)', en: 'Free Time (days)' },
  'quotes.route': { pt: 'Rota', en: 'Route' },
  'quotes.zero_charge_confirm': { pt: 'Deseja inserir uma taxa com valor zero?', en: 'Do you want to add a zero-value tax?' },
  'quotes.add_to_catalog': { pt: '+ Adicionar ao catálogo', en: '+ Add to catalog' },

  // Quote statuses
  'quote_status.draft': { pt: 'Rascunho', en: 'Draft' },
  'quote_status.quoting': { pt: 'Cotando', en: 'Quoting' },
  'quote_status.sent': { pt: 'Enviada', en: 'Sent' },
  'quote_status.approved': { pt: 'Aprovada', en: 'Approved' },
  'quote_status.rejected': { pt: 'Rejeitada', en: 'Rejected' },
  'quote_status.converted': { pt: 'Convertida', en: 'Converted' },

  // Registrations
  'registrations.title': { pt: 'Cadastros', en: 'Registrations' },
  'registrations.new': { pt: 'Novo Cadastro', en: 'New Registration' },
  'registrations.search': { pt: 'Buscar por nome ou CNPJ...', en: 'Search by name or tax ID...' },
  'registrations.clients': { pt: 'Clientes', en: 'Clients' },
  'registrations.suppliers': { pt: 'Fornecedores', en: 'Suppliers' },
  'registrations.carriers': { pt: 'Armadores', en: 'Carriers' },
  'registrations.agents': { pt: 'Agentes', en: 'Agents' },
  'registrations.all': { pt: 'Todos', en: 'All' },
  'registrations.add_new_type': { pt: '+ Adicionar novo tipo', en: '+ Add new type' },
  'registrations.new_type_placeholder': { pt: 'Digite o novo tipo...', en: 'Enter new type...' },
  'registrations.name': { pt: 'Razão Social', en: 'Company Name' },
  'registrations.tax_id': { pt: 'CNPJ', en: 'Tax ID' },
  'registrations.contact': { pt: 'Contato', en: 'Contact' },
  'registrations.email': { pt: 'E-mail', en: 'Email' },
  'registrations.phone': { pt: 'Telefone', en: 'Phone' },
  'registrations.address': { pt: 'Endereço', en: 'Address' },
  'registrations.type': { pt: 'Tipo', en: 'Type' },
  'registrations.lookup_cnpj': { pt: 'Consultar CNPJ', en: 'Lookup Tax ID' },
  'registrations.cnpj_not_found': { pt: 'CNPJ não encontrado', en: 'Tax ID not found' },
  'registrations.cnpj_already_exists': { pt: 'Este CNPJ já está cadastrado', en: 'This tax ID is already registered' },
  'registrations.cnpj_found': { pt: 'Dados preenchidos automaticamente', en: 'Data auto-filled' },
  'registrations.type_client': { pt: 'Cliente', en: 'Client' },
  'registrations.type_supplier': { pt: 'Fornecedor', en: 'Supplier' },
  'registrations.type_carrier': { pt: 'Armador', en: 'Carrier' },
  'registrations.type_agent': { pt: 'Agente', en: 'Agent' },
  'registrations.salesperson': { pt: 'Vendedor', en: 'Salesperson' },
  'registrations.select_salesperson': { pt: 'Selecionar vendedor...', en: 'Select salesperson...' },
  'registrations.commission_rate': { pt: 'Comissão (%)', en: 'Commission (%)' },
  'registrations.tracking_link': { pt: 'Link de Rastreamento', en: 'Tracking Link' },
  'registrations.link_copied': { pt: 'Link copiado!', en: 'Link copied!' },
  'registrations.partner_category': { pt: 'Categoria do Parceiro', en: 'Partner Category' },
  'registrations.category_road_carrier': { pt: 'Transportadora (Rodoviário)', en: 'Road Carrier' },
  'registrations.category_insurance': { pt: 'Seguradora', en: 'Insurance' },
  'registrations.category_co_loader': { pt: 'Co-loader', en: 'Co-loader' },
  'registrations.category_ocean_carrier': { pt: 'Armador (Marítimo)', en: 'Ocean Carrier' },
  'registrations.category_air_carrier': { pt: 'Cia Aérea', en: 'Air Carrier' },
  'registrations.category_terminal': { pt: 'Terminal', en: 'Terminal' },
  'registrations.category_other': { pt: 'Outros', en: 'Others' },

  // Commission
  'dashboard.commission_available': { pt: 'Comissão Liberada', en: 'Commission Available' },
  'dashboard.commission_subtitle': { pt: 'Processos finalizados até o mês anterior', en: 'Completed processes up to last month' },
  'dashboard.commission_forecast': { pt: 'Comissão Prevista', en: 'Forecasted Commission' },
  'dashboard.commission_forecast_subtitle': { pt: 'Processos em andamento', en: 'Ongoing processes' },
  'dashboard.commission_forecast_warning': { pt: '⚠️ Os valores de comissão prevista podem sofrer alterações até a finalização e pagamento completo dos processos.', en: '⚠️ Forecasted commission values may change until processes are fully completed and paid.' },

  // Financial page
  'financial.page_title': { pt: 'Financeiro', en: 'Financial' },
  'financial.charges': { pt: 'Cobranças', en: 'Charges' },
  'financial.payables': { pt: 'Compras', en: 'Payables' },
  'financial.receivables': { pt: 'Vendas', en: 'Receivables' },
  'financial.profit': { pt: 'Lucro', en: 'Profit' },
  'financial.margin': { pt: 'Margem', en: 'Margin' },
  'financial.tax': { pt: 'Imposto', en: 'Tax' },
  'financial.total': { pt: 'Total', en: 'Total' },
  'financial.currency': { pt: 'Moeda', en: 'Currency' },
  'financial.total_profit': { pt: 'Lucro Total', en: 'Total Profit' },
  'financial.avg_margin': { pt: 'Margem Média', en: 'Avg. Margin' },
  'financial.by_shipment': { pt: 'Por Embarque', en: 'By Shipment' },
  'financial.add_cost': { pt: 'Compra', en: 'Add Cost' },
  'financial.add_revenue': { pt: 'Venda', en: 'Add Revenue' },
  'financial.partner': { pt: 'Empresa', en: 'Company' },
  'financial.no_partner': { pt: 'Sem empresa', en: 'No company' },
  'financial.partner_required': { pt: 'Selecione uma empresa antes de adicionar a taxa.', en: 'Please select a company before adding the charge.' },
  'financial.select_partner': { pt: 'Selecionar empresa...', en: 'Select company...' },
  'financial.charge_type': { pt: 'Trecho', en: 'Leg' },
  'financial.description': { pt: 'Descrição', en: 'Description' },
  'financial.partners_tab': { pt: 'Empresas do Processo', en: 'Process Companies' },
  'financial.add_partner': { pt: 'Adicionar Empresa', en: 'Add Company' },
  'financial.search_partner': { pt: 'Buscar empresa...', en: 'Search company...' },
  'financial.no_partners_msg': { pt: 'Adicione os parceiros envolvidos neste processo para usá-los nas charges.', en: 'Add partners involved in this process to use them in charges.' },
  'financial.amount': { pt: 'Valor', en: 'Amount' },
  'financial.exchange_rate': { pt: 'Câmbio', en: 'Exchange Rate' },
  'financial.subtotal': { pt: 'Subtotal', en: 'Subtotal' },
  'financial.summary_by_currency': { pt: 'Resumo por Moeda', en: 'Summary by Currency' },
  'financial.profit_by_currency': { pt: 'Lucro por Moeda', en: 'Profit by Currency' },
  'financial.charge_added': { pt: 'Taxa adicionada', en: 'Tax added' },
  'financial.pending_invoices': { pt: 'faturas pendentes', en: 'pending invoices' },
  'financial.status_pending': { pt: 'Pendente', en: 'Pending' },
  'financial.status_invoiced': { pt: 'Faturado', en: 'Invoiced' },
  'financial.status_paid': { pt: 'Pago', en: 'Paid' },
  'financial.invoice_number': { pt: 'Nº Fatura', en: 'Invoice #' },
  'financial.current_rate': { pt: 'Cotação atual', en: 'Current rate' },
  'financial.update_rate': { pt: 'Atualizar cotação', en: 'Update rate' },
  'financial.verify': { pt: 'Conferir', en: 'Verify' },
  'financial.charge_verified': { pt: 'Taxa conferida', en: 'Tax verified' },
  'financial.supplier_amount': { pt: 'Valor Fornecedor', en: 'Supplier Amount' },
  'financial.release_to_financial': { pt: 'Liberar para Financeiro', en: 'Release to Financial' },
  'financial.released_success': { pt: 'Liberado para o Financeiro', en: 'Released to Financial' },
  'financial.status_updated': { pt: 'Status atualizado', en: 'Status updated' },
  'financial.pending_verification_msg': { pt: 'Taxas pendentes de conferência pelo operacional. Compare os valores cotados com os cobrados pelo fornecedor.', en: 'Taxes pending verification by operations. Compare quoted vs supplier amounts.' },
  'financial.pending_payment_msg': { pt: 'Processo liberado para pagamento. Todas as taxas devem ser pagas para encerrar o processo.', en: 'Process released for payment. All charges must be paid to close the process.' },
  'financial.all_paid_msg': { pt: 'Todas as taxas foram pagas. O processo pode ser encerrado.', en: 'All charges are paid. The process can be closed.' },
  'financial.all_charges_must_be_paid': { pt: '⚠️ Todas as taxas devem estar pagas para encerrar este processo.', en: '⚠️ All charges must be paid before closing this process.' },
  'quotes.current_dollar': { pt: 'Dólar hoje', en: 'Dollar today' },
  'quotes.current_euro': { pt: 'Euro hoje', en: 'Euro today' },
  'quotes.exchange_reference': { pt: 'Referência de câmbio', en: 'Exchange reference' },

  // Benchmarks
  'financial.benchmarks': { pt: 'Benchmarks de Rota', en: 'Route Benchmarks' },
  'financial.client_avg_profit': { pt: 'Profit médio deste cliente', en: 'Client avg. profit' },
  'financial.market_avg_profit': { pt: 'Profit médio geral', en: 'Market avg. profit' },
  'financial.based_on_n_shipments': { pt: 'processos', en: 'shipments' },
  'financial.no_route_data': { pt: 'Sem dados para esta rota', en: 'No data for this route' },
  'financial.same_route': { pt: 'Mesma rota', en: 'Same route' },
  'financial.above_avg': { pt: 'acima da média', en: 'above avg' },
  'financial.below_avg': { pt: 'abaixo da média', en: 'below avg' },

  // Auth
  'auth.login': { pt: 'Entrar', en: 'Sign In' },
  'auth.signup': { pt: 'Cadastrar', en: 'Sign Up' },
  'auth.email': { pt: 'E-mail', en: 'Email' },
  'auth.password': { pt: 'Senha', en: 'Password' },
  'auth.company_name': { pt: 'Nome da Empresa', en: 'Company Name' },
  'auth.full_name': { pt: 'Nome Completo', en: 'Full Name' },
  'auth.no_account': { pt: 'Não tem conta?', en: "Don't have an account?" },
  'auth.has_account': { pt: 'Já tem conta?', en: 'Already have an account?' },
  'auth.create_account': { pt: 'Criar Conta', en: 'Create Account' },
  'auth.signing_in': { pt: 'Entrando...', en: 'Signing in...' },
  'auth.creating': { pt: 'Criando conta...', en: 'Creating account...' },
  'auth.check_email': { pt: 'Verifique seu e-mail para confirmar o cadastro', en: 'Check your email to confirm your registration' },
  'auth.forgot_password': { pt: 'Esqueceu sua senha?', en: 'Forgot your password?' },
  'auth.reset_password': { pt: 'Recuperar Senha', en: 'Reset Password' },
  'auth.reset_email_sent': { pt: 'E-mail de recuperação enviado! Verifique sua caixa de entrada.', en: 'Recovery email sent! Check your inbox.' },
  'auth.new_password': { pt: 'Nova Senha', en: 'New Password' },
  'auth.new_password_desc': { pt: 'Digite sua nova senha abaixo.', en: 'Enter your new password below.' },
  'auth.confirm_password': { pt: 'Confirmar Senha', en: 'Confirm Password' },
  'auth.update_password': { pt: 'Atualizar Senha', en: 'Update Password' },
  'auth.passwords_no_match': { pt: 'As senhas não coincidem.', en: 'Passwords do not match.' },
  'auth.password_updated': { pt: 'Senha atualizada com sucesso!', en: 'Password updated successfully!' },
  'auth.invalid_recovery_link': { pt: 'Link de recuperação inválido ou expirado.', en: 'Invalid or expired recovery link.' },
  'auth.send_reset_link': { pt: 'Enviar Link', en: 'Send Link' },
  'auth.back_to_login': { pt: 'Voltar ao Login', en: 'Back to Login' },

  // Settings
  'settings.title': { pt: 'Configurações', en: 'Settings' },
  'settings.company': { pt: 'Empresa', en: 'Company' },
  'settings.users': { pt: 'Usuários', en: 'Users' },
  'settings.language': { pt: 'Idioma', en: 'Language' },
  'settings.quote_prefix': { pt: 'Prefixo das Cotações', en: 'Quote Prefix' },
  'settings.quote_prefix_hint': { pt: 'Ex: FF gera FF-00001. Máx 5 caracteres.', en: 'E.g. FF generates FF-00001. Max 5 chars.' },
  'settings.company_logo': { pt: 'Logo da Empresa', en: 'Company Logo' },
  'settings.upload_logo': { pt: 'Enviar Logo', en: 'Upload Logo' },
  'settings.remove_logo': { pt: 'Remover', en: 'Remove' },
  'settings.logo_hint': { pt: 'PNG ou JPG, máx 2MB. Será exibido no menu lateral e nos PDFs.', en: 'PNG or JPG, max 2MB. Shown in sidebar and PDFs.' },
  'settings.save': { pt: 'Salvar', en: 'Save' },
  'settings.user_role': { pt: 'Cargo', en: 'Role' },
  'settings.role_updated': { pt: 'Cargo atualizado', en: 'Role updated' },
  'settings.select_role': { pt: 'Selecionar cargo...', en: 'Select role...' },
  'registrations.edit': { pt: 'Editar Cadastro', en: 'Edit Registration' },
  'registrations.foreign_company': { pt: 'EXTERIOR', en: 'FOREIGN' },

  // Common
  'common.save': { pt: 'Salvar', en: 'Save' },
  'common.copy_summary': { pt: 'Copiar Resumo', en: 'Copy Summary' },
  'common.copied': { pt: 'Copiado!', en: 'Copied!' },
  'common.cancel': { pt: 'Cancelar', en: 'Cancel' },
  'common.delete': { pt: 'Excluir', en: 'Delete' },
  'common.edit': { pt: 'Editar', en: 'Edit' },
  'common.create': { pt: 'Criar', en: 'Create' },
  'common.search': { pt: 'Buscar...', en: 'Search...' },
  'common.filter': { pt: 'Filtrar', en: 'Filter' },
  'common.export': { pt: 'Exportar', en: 'Export' },
  'common.loading': { pt: 'Carregando...', en: 'Loading...' },
  'common.no_data': { pt: 'Nenhum dado encontrado', en: 'No data found' },
  'common.upload': { pt: 'Enviar Arquivo', en: 'Upload' },
  'common.actions': { pt: 'Ações', en: 'Actions' },
  'common.notifications': { pt: 'Notificações', en: 'Notifications' },
  'common.no_notifications': { pt: 'Nenhuma notificação', en: 'No notifications' },
  'common.confirm': { pt: 'Confirmar', en: 'Confirm' },
  'registrations.close_confirm': { pt: 'Existem dados preenchidos. Deseja realmente sair sem salvar?', en: 'There is unsaved data. Do you really want to leave without saving?' },

  // Tasks
  'tasks.request_booking': { pt: 'Solicitar Booking', en: 'Request Booking' },
  'tasks.send_followup': { pt: 'Enviar Follow-up ao Cliente', en: 'Send Follow-up to Client' },
  'common.support_contact': { pt: 'Dúvidas? contato@brasadigital.com.br', en: 'Questions? contato@brasadigital.com.br' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt');

  const t = useCallback((key: string): string => {
    return translations[key]?.[language] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
