
-- Ports and airports reference table
CREATE TABLE public.ports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  city text,
  country_code text NOT NULL,
  country_name text,
  type text NOT NULL DEFAULT 'sea' CHECK (type IN ('sea', 'air', 'both')),
  latitude numeric,
  longitude numeric
);

-- Public read access
ALTER TABLE public.ports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read ports" ON public.ports FOR SELECT TO authenticated USING (true);

-- Seed: Major Brazilian ports
INSERT INTO public.ports (code, name, city, country_code, country_name, type) VALUES
('BRSSZ', 'Porto de Santos', 'Santos', 'BR', 'Brasil', 'sea'),
('BRPNG', 'Porto de Paranaguá', 'Paranaguá', 'BR', 'Brasil', 'sea'),
('BRRIG', 'Porto de Rio Grande', 'Rio Grande', 'BR', 'Brasil', 'sea'),
('BRITJ', 'Porto de Itajaí', 'Itajaí', 'BR', 'Brasil', 'sea'),
('BRNVT', 'Porto de Navegantes', 'Navegantes', 'BR', 'Brasil', 'sea'),
('BRRIO', 'Porto do Rio de Janeiro', 'Rio de Janeiro', 'BR', 'Brasil', 'sea'),
('BRVIX', 'Porto de Vitória', 'Vitória', 'BR', 'Brasil', 'sea'),
('BRSSA', 'Porto de Salvador', 'Salvador', 'BR', 'Brasil', 'sea'),
('BRSUA', 'Porto de Suape', 'Ipojuca', 'BR', 'Brasil', 'sea'),
('BRFOR', 'Porto de Fortaleza', 'Fortaleza', 'BR', 'Brasil', 'sea'),
('BRSLZ', 'Porto de São Luís', 'São Luís', 'BR', 'Brasil', 'sea'),
('BRBEL', 'Porto de Belém', 'Belém', 'BR', 'Brasil', 'sea'),
('BRMAO', 'Porto de Manaus', 'Manaus', 'BR', 'Brasil', 'sea'),
('BRSFZ', 'Porto de São Francisco do Sul', 'São Francisco do Sul', 'BR', 'Brasil', 'sea'),
('BRIMB', 'Porto de Imbituba', 'Imbituba', 'BR', 'Brasil', 'sea'),
-- Major Brazilian airports
('GRU', 'Aeroporto de Guarulhos', 'São Paulo', 'BR', 'Brasil', 'air'),
('VCP', 'Aeroporto de Viracopos', 'Campinas', 'BR', 'Brasil', 'air'),
('GIG', 'Aeroporto do Galeão', 'Rio de Janeiro', 'BR', 'Brasil', 'air'),
('CWB', 'Aeroporto Afonso Pena', 'Curitiba', 'BR', 'Brasil', 'air'),
('POA', 'Aeroporto Salgado Filho', 'Porto Alegre', 'BR', 'Brasil', 'air'),
('CNF', 'Aeroporto de Confins', 'Belo Horizonte', 'BR', 'Brasil', 'air'),
('REC', 'Aeroporto do Recife', 'Recife', 'BR', 'Brasil', 'air'),
('SSA', 'Aeroporto de Salvador', 'Salvador', 'BR', 'Brasil', 'air'),
('MAO', 'Aeroporto Eduardo Gomes', 'Manaus', 'BR', 'Brasil', 'air'),
-- Major global seaports
('CNSHA', 'Port of Shanghai', 'Shanghai', 'CN', 'China', 'sea'),
('CNNGB', 'Port of Ningbo-Zhoushan', 'Ningbo', 'CN', 'China', 'sea'),
('CNSHE', 'Port of Shenzhen', 'Shenzhen', 'CN', 'China', 'sea'),
('CNQIN', 'Port of Qingdao', 'Qingdao', 'CN', 'China', 'sea'),
('CNTIA', 'Port of Tianjin', 'Tianjin', 'CN', 'China', 'sea'),
('CNXMN', 'Port of Xiamen', 'Xiamen', 'CN', 'China', 'sea'),
('SGSIN', 'Port of Singapore', 'Singapore', 'SG', 'Singapura', 'sea'),
('NLRTM', 'Port of Rotterdam', 'Rotterdam', 'NL', 'Holanda', 'sea'),
('NLAMS', 'Port of Amsterdam', 'Amsterdam', 'NL', 'Holanda', 'sea'),
('DEHAM', 'Port of Hamburg', 'Hamburg', 'DE', 'Alemanha', 'sea'),
('DEBRE', 'Port of Bremerhaven', 'Bremerhaven', 'DE', 'Alemanha', 'sea'),
('BEANR', 'Port of Antwerp', 'Antwerp', 'BE', 'Bélgica', 'sea'),
('GBFXT', 'Port of Felixstowe', 'Felixstowe', 'GB', 'Reino Unido', 'sea'),
('GBSOU', 'Port of Southampton', 'Southampton', 'GB', 'Reino Unido', 'sea'),
('GBLGP', 'London Gateway Port', 'London', 'GB', 'Reino Unido', 'sea'),
('FRLEH', 'Port of Le Havre', 'Le Havre', 'FR', 'França', 'sea'),
('ESBCN', 'Port of Barcelona', 'Barcelona', 'ES', 'Espanha', 'sea'),
('ESALG', 'Port of Algeciras', 'Algeciras', 'ES', 'Espanha', 'sea'),
('ESVLC', 'Port of Valencia', 'Valencia', 'ES', 'Espanha', 'sea'),
('ITGOA', 'Port of Genoa', 'Genoa', 'IT', 'Itália', 'sea'),
('ITGIT', 'Port of Gioia Tauro', 'Gioia Tauro', 'IT', 'Itália', 'sea'),
('GRPIR', 'Port of Piraeus', 'Piraeus', 'GR', 'Grécia', 'sea'),
('TRIST', 'Port of Istanbul', 'Istanbul', 'TR', 'Turquia', 'sea'),
('AEJEA', 'Jebel Ali Port', 'Dubai', 'AE', 'Emirados Árabes', 'sea'),
('KRPUS', 'Port of Busan', 'Busan', 'KR', 'Coreia do Sul', 'sea'),
('JPYOK', 'Port of Yokohama', 'Yokohama', 'JP', 'Japão', 'sea'),
('JPTYO', 'Port of Tokyo', 'Tokyo', 'JP', 'Japão', 'sea'),
('JPKOB', 'Port of Kobe', 'Kobe', 'JP', 'Japão', 'sea'),
('THLCH', 'Laem Chabang Port', 'Laem Chabang', 'TH', 'Tailândia', 'sea'),
('VNSGN', 'Port of Ho Chi Minh', 'Ho Chi Minh City', 'VN', 'Vietnã', 'sea'),
('MYPKG', 'Port Klang', 'Port Klang', 'MY', 'Malásia', 'sea'),
('INMUN', 'Mundra Port', 'Mundra', 'IN', 'Índia', 'sea'),
('INNSA', 'Nhava Sheva Port', 'Mumbai', 'IN', 'Índia', 'sea'),
('INCHE', 'Port of Chennai', 'Chennai', 'IN', 'Índia', 'sea'),
('USNYC', 'Port of New York/New Jersey', 'New York', 'US', 'Estados Unidos', 'sea'),
('USLAX', 'Port of Los Angeles', 'Los Angeles', 'US', 'Estados Unidos', 'sea'),
('USLGB', 'Port of Long Beach', 'Long Beach', 'US', 'Estados Unidos', 'sea'),
('USSAV', 'Port of Savannah', 'Savannah', 'US', 'Estados Unidos', 'sea'),
('USHOU', 'Port of Houston', 'Houston', 'US', 'Estados Unidos', 'sea'),
('USMIA', 'Port of Miami', 'Miami', 'US', 'Estados Unidos', 'sea'),
('USSEA', 'Port of Seattle/Tacoma', 'Seattle', 'US', 'Estados Unidos', 'sea'),
('MXMAN', 'Port of Manzanillo', 'Manzanillo', 'MX', 'México', 'sea'),
('MXVER', 'Port of Veracruz', 'Veracruz', 'MX', 'México', 'sea'),
('ARBUE', 'Port of Buenos Aires', 'Buenos Aires', 'AR', 'Argentina', 'sea'),
('CLSAI', 'Port of San Antonio', 'San Antonio', 'CL', 'Chile', 'sea'),
('CLVAP', 'Port of Valparaíso', 'Valparaíso', 'CL', 'Chile', 'sea'),
('PECLL', 'Port of Callao', 'Callao', 'PE', 'Peru', 'sea'),
('COBUN', 'Port of Buenaventura', 'Buenaventura', 'CO', 'Colômbia', 'sea'),
('EGPSD', 'Port Said', 'Port Said', 'EG', 'Egito', 'sea'),
('ZADUR', 'Port of Durban', 'Durban', 'ZA', 'África do Sul', 'sea'),
('AUMEL', 'Port of Melbourne', 'Melbourne', 'AU', 'Austrália', 'sea'),
('AUSYD', 'Port of Sydney', 'Sydney', 'AU', 'Austrália', 'sea'),
-- Major global airports
('PVG', 'Shanghai Pudong Intl', 'Shanghai', 'CN', 'China', 'air'),
('HKG', 'Hong Kong Intl', 'Hong Kong', 'HK', 'Hong Kong', 'air'),
('SIN', 'Changi Airport', 'Singapore', 'SG', 'Singapura', 'air'),
('ICN', 'Incheon Intl', 'Seoul', 'KR', 'Coreia do Sul', 'air'),
('NRT', 'Narita Intl', 'Tokyo', 'JP', 'Japão', 'air'),
('AMS', 'Schiphol Airport', 'Amsterdam', 'NL', 'Holanda', 'air'),
('FRA', 'Frankfurt Airport', 'Frankfurt', 'DE', 'Alemanha', 'air'),
('LHR', 'Heathrow Airport', 'London', 'GB', 'Reino Unido', 'air'),
('CDG', 'Charles de Gaulle', 'Paris', 'FR', 'França', 'air'),
('DXB', 'Dubai Intl', 'Dubai', 'AE', 'Emirados Árabes', 'air'),
('JFK', 'John F. Kennedy Intl', 'New York', 'US', 'Estados Unidos', 'air'),
('LAX', 'Los Angeles Intl', 'Los Angeles', 'US', 'Estados Unidos', 'air'),
('ORD', 'O''Hare Intl', 'Chicago', 'US', 'Estados Unidos', 'air'),
('MIA', 'Miami Intl', 'Miami', 'US', 'Estados Unidos', 'air'),
('ATL', 'Hartsfield-Jackson Intl', 'Atlanta', 'US', 'Estados Unidos', 'air'),
('MEM', 'Memphis Intl', 'Memphis', 'US', 'Estados Unidos', 'air'),
('EZE', 'Ministro Pistarini', 'Buenos Aires', 'AR', 'Argentina', 'air'),
('SCL', 'Arturo Merino Benítez', 'Santiago', 'CL', 'Chile', 'air'),
('BOG', 'El Dorado Intl', 'Bogotá', 'CO', 'Colômbia', 'air'),
('MEX', 'Mexico City Intl', 'Cidade do México', 'MX', 'México', 'air'),
('LIM', 'Jorge Chávez Intl', 'Lima', 'PE', 'Peru', 'air'),
('DOH', 'Hamad Intl', 'Doha', 'QA', 'Catar', 'air'),
('BOM', 'Chhatrapati Shivaji', 'Mumbai', 'IN', 'Índia', 'air'),
('SYD', 'Sydney Kingsford Smith', 'Sydney', 'AU', 'Austrália', 'air'),
('LUX', 'Luxembourg Airport', 'Luxembourg', 'LU', 'Luxemburgo', 'air'),
('LEJ', 'Leipzig/Halle Airport', 'Leipzig', 'DE', 'Alemanha', 'air'),
('LGG', 'Liège Airport', 'Liège', 'BE', 'Bélgica', 'air'),
('IST', 'Istanbul Airport', 'Istanbul', 'TR', 'Turquia', 'air'),
('NBO', 'Jomo Kenyatta Intl', 'Nairobi', 'KE', 'Quênia', 'air'),
('JNB', 'O.R. Tambo Intl', 'Johannesburg', 'ZA', 'África do Sul', 'air');
